Remove Automata mainnet and contextfree testnet
polkadot-js/apps pull request #10531
Opened 2024-05-03 03:02 UTC by Liao1

2024-05-20 13:33 UTC, TarikGul requested changes
Conflicts just need to be resolved.

2024-05-21 02:30 UTC, Liao1 commented
> Conflicts just need to be resolved.

Hi @TarikGul , conflicts resolved, is there anything else I should do to get the pr merged?

2024-05-24 07:24 UTC, Liao1 commented
> The `/api/spec/automata.ts` file also needs to be removed as well?

Hi @TarikGul , `automata.ts` removed.

2024-05-24 15:39 UTC, TarikGul approved these changes

2024-05-24 15:39 UTC, merged