Add communeai
polkadot-js/apps pull request #10630
Opened 2024-06-01 17:08 UTC by EdSDR

This PR adds the Commune AI to the Live networks section.

Network: Commune AI
Website: https://communeai.org/
Symbol: COMAI
Decimals: 9
ss58 format: 13116, 42
Discord: https://discord.gg/communeai
Twitter: https://x.com/communeaidotorg
Github (main): https://github.com/commune-ai
Github (substrate node): https://github.com/commune-ai/subspace

2024-06-11 17:02 UTC, Supremesource commented
@jakobilobi Any progress here ?

2024-06-12 08:43 UTC, jakobilobi commented
I'm not involved here, guessing you meant to tag someone else?

2024-06-12 12:23 UTC, TarikGul requested changes
You need to export the api/spec typesbundle from `api/spec/index.ts`

2024-06-14 13:40 UTC, TarikGul approved these changes

2024-06-14 13:40 UTC, merged