fix(paseo): relay for identity
polkadot-js/apps pull request #10651
Opened 2024-06-07 19:57 UTC by al3mart

I have noticed several changes regarding the identity pallet, its types and how it is displayed in the app.

@validorange has reposted that setting an identity was not available in the accounts tab.

I believe this change should re-enable that and and use legacy identities instead of People chain ids. Please, point me in the right direction if that is not the case @TarikGul

2024-06-07 22:26 UTC, TarikGul commented
Yea I think that should do it, thanks for the fix!

2024-06-07 22:26 UTC, TarikGul approved these changes

2024-06-07 22:31 UTC, TarikGul commented
Ahh actually, there needs to be one more addition, since its a relay chain: 

https://github.com/polkadot-js/apps/blob/master/packages/react-api/src/Api.tsx#L302

Needs to have `paseo` added to it as well. Unfortunately it's hard coded for now since everything is going to be transferred to the identity chain for all relays.

2024-06-07 22:47 UTC, TarikGul requested changes
Changes the status: My bad for approving earlier

2024-06-09 16:43 UTC, al3mart commented
Thanks!

I have added a check for `paseo` following how the check for `polkadot` has been made.
Saw this at first, but was not sure if my first change was enough

2024-06-10 23:46 UTC, TarikGul approved these changes
Nice job, thanks for updating it!

2024-06-10 23:46 UTC, merged