Add RegionX Cocos
polkadot-js/apps pull request #10696
Opened 2024-06-23 18:12 UTC by Szegoo

This PR is a request to add the RegionX test parachain called 'Cocos' to Polkadot.js.

2024-06-27 07:43 UTC, Szegoo commented
@TarikGul I updated the order

2024-06-28 14:52 UTC, TarikGul requested changes
Looks like another ordering issues, It is kind of silly but it does 1 level at a time, so maybe run `yarn test` locally after fixing it or try to see where the it should be manually in the order.

2024-06-29 13:00 UTC, Szegoo commented
@TarikGul Checked with `yarn test` locally, should be good now.

2024-07-01 14:15 UTC, TarikGul approved these changes

2024-07-01 14:15 UTC, merged