feat: added niskala testnet to paseo
polkadot-js/apps pull request #10760
Opened 2024-07-17 03:52 UTC by zianksm

2024-07-17 03:59 UTC, zianksm commented
Ready for review!

2024-07-17 13:37 UTC, TarikGul approved these changes

2024-07-17 13:55 UTC, TarikGul requested changes
The ordering just needs to be corrected in `testingRelayPaseo.ts`

2024-07-18 01:55 UTC, zianksm commented
Done!

2024-07-18 13:46 UTC, TarikGul approved these changes

2024-07-18 13:46 UTC, merged