Adds new Hyperbridge logo
polkadot-js/apps pull request #10822
Opened 2024-08-12 20:38 UTC by olahfemi

2024-08-12 20:45 UTC, TarikGul requested changes
Looks like image size is causing issues. Please resize the image - you can reproduce the error by running `yarn build:code`

2024-08-12 21:00 UTC, olahfemi commented
> Looks like image size is causing issues. Please resize the image - you can reproduce the error by running `yarn build:code`

Ok. On it.

2024-08-12 21:08 UTC, olahfemi commented
> Looks like image size is causing issues. Please resize the image - you can reproduce the error by running `yarn build:code`

Fixed. Can it be merged now?

2024-08-13 14:15 UTC, TarikGul approved these changes

2024-08-13 14:15 UTC, merged