update xcavate logo
polkadot-js/apps pull request #10911
Opened 2024-09-11 13:36 UTC by ganesh1997oli

2024-09-12 12:31 UTC, TarikGul requested changes
2 fixes required. Linter, and decreasing the image size

2024-09-12 14:51 UTC, ganesh1997oli commented
> 2 fixes required. Linter, and decreasing the image size

all checks have passed

2024-09-13 14:05 UTC, ganesh1997oli commented
> > 2 fixes required. Linter, and decreasing the image size
> 
> all checks have passed

hey @TarikGul would you mind merging, please!

2024-09-16 10:10 UTC, ganesh1997oli commented
> > > 2 fixes required. Linter, and decreasing the image size
> > 
> > 
> > all checks have passed
> 
> hey @TarikGul

hey @TarikGul, does it take long time to merge this PR?

2024-09-16 11:29 UTC, TarikGul requested changes
I think the last logo needs to be removed completely no?

2024-09-16 13:39 UTC, ganesh1997oli commented
> I think the last logo needs to be removed completely no?

yes completely!

2024-09-17 03:13 UTC, ganesh1997oli commented
Suddenly it PR shows conflict and after fixing I get test fails, can you tell me which test fail?

2024-09-17 11:30 UTC, TarikGul reviewed
Also as mentioned you need to remove the old PNG - `chainsXcavatePNG`. It's not being used anymore so it shouldn't be in the repo.

2024-09-17 11:30 UTC, TarikGul commented on packages/apps-config/src/endpoints/testingRelayPaseo.ts
> +    homepage: 'zeitgeist.pm',
It's saying this is a duplicate, when you were fixing conflicts it looks like you fixed them wrong.

2024-09-18 02:05 UTC, closed without merging