Update calamari crowdloan UI and Dropdown menu
polkadot-js/apps pull request #6021
Opened 2021-08-28 10:42 UTC by Dengjianping

We're going to participate next round of slot auction, so we have to update calamari crowdloan UI and dropdown menu.
Please check.
Thanks!

2021-08-28 13:17 UTC, jacogr requested changes

2021-08-28 13:17 UTC, jacogr commented on packages/apps-config/src/endpoints/production.ts
> +    },
Can only be as a parachain under relays, or as a stand-alone chain, not both.
```suggestion
```

2021-08-28 15:41 UTC, stechu commented
@jacogr  thanks! just updated.

2021-08-29 07:17 UTC, jacogr approved these changes

2021-08-29 07:17 UTC, merged