Add Polkadex parathread/parachain information
polkadot-js/apps pull request #6839
Opened 2022-01-17 13:56 UTC by arrudagates

This PR adds information for the ui to display Polkadex parathread data.

2022-01-17 15:41 UTC, jacogr requested changes
Thank you. 

Some CI linting issues, spaces vs tabs - https://github.com/polkadot-js/apps/runs/4842909982?check_suite_focus=true#step:3:689

I also believe the ordering may be incorrect here, generally would like the names in alphabetical order. (There is a test on CI that runs that will fail if not)

2022-01-18 07:12 UTC, jacogr commented on packages/apps-config/src/endpoints/productionRelayPolkadot.ts
> +        	'Polkadex Team': 'wss://mainnet.polkadex.trade/'
```suggestion
          'Polkadex Team': 'wss://mainnet.polkadex.trade/'
```

2022-01-18 11:05 UTC, jacogr requested changes
After the linting fix applied above, CI is indeed failing on the alphabetical ordering - https://github.com/polkadot-js/apps/runs/4852151797?check_suite_focus=true#step:3:753

2022-01-19 05:10 UTC, simonsso commented on packages/apps-config/src/endpoints/productionRelayPolkadot.ts
> +        	'Polkadex Team': 'wss://mainnet.polkadex.trade/'
The URL is good

2022-01-19 15:33 UTC, jacogr approved these changes

2022-01-19 15:33 UTC, merged