Add ajuna network
polkadot-js/apps pull request #6979
Opened 2022-02-13 23:01 UTC by cowboy-bebug

This PR adds app configuration for Ajuna Network.
Thanks.

2022-02-14 07:45 UTC, jacogr requested changes
CI fails on some linting checks, apart from that looks good.

2022-02-14 07:45 UTC, jacogr commented on packages/apps-config/src/api/spec/ajuna.ts
> +        LookupSource: 'MultiAddress',
Linting fails here, see https://github.com/polkadot-js/apps/runs/5180186370?check_suite_focus=true#step:3:696

2022-02-14 07:45 UTC, jacogr commented on packages/apps-config/src/ui/colors.ts
> +  Ajuna: chainAjuna,
Sort order, https://github.com/polkadot-js/apps/runs/5180186370?check_suite_focus=true#step:3:699

2022-02-14 21:17 UTC, cowboy-bebug commented on packages/apps-config/src/api/spec/ajuna.ts
> +        LookupSource: 'MultiAddress',
Thanks!

2022-02-14 21:18 UTC, cowboy-bebug commented on packages/apps-config/src/ui/colors.ts
> +  Ajuna: chainAjuna,
Thanks!

2022-02-14 21:29 UTC, cowboy-bebug commented
Thanks 🙏 could you re-run the workflows?

2022-02-15 05:32 UTC, jacogr requested changes

2022-02-15 05:32 UTC, jacogr commented on packages/apps-config/src/endpoints/testing.ts
> +    {
Sort alphabetically, see https://github.com/polkadot-js/apps/runs/5195053157?check_suite_focus=true#step:3:759

2022-02-15 19:17 UTC, cowboy-bebug commented on packages/apps-config/src/endpoints/testing.ts
> +    {
Thanks

2022-02-16 06:06 UTC, jacogr approved these changes

2022-02-16 06:11 UTC, merged