Add OnFinality endpoint for Crust and make it reachable
polkadot-js/apps pull request #7032
Opened 2022-02-24 07:16 UTC by banananeko

2022-02-24 08:00 UTC, jacogr requested changes
Is this connected as a parachain to the Polkadot relay?

It has produced 3M blocks already on both RPCs. The first parachain that went in is on 700k blocks and is actually in the Polkadot set.

These are only for parachains that are connected to the relay.

2022-02-25 05:24 UTC, jacogr requested changes
As commented, I would not remove the parachain config since that has a negative impact on mapping the paraId to your name which means it won't show up as a named parathread nor in the crowdloans. 

Additionally the `isDisabled` flag should be removed from `endpoints/production` to make it active.

2022-02-25 05:24 UTC, jacogr commented on packages/apps-config/src/endpoints/productionRelayPolkadot.ts
> -        text: t('rpc.polkadot.crust', 'Crust', { ns: 'apps-config' }),
By removing this, it won't show up here -

![image](https://user-images.githubusercontent.com/1424473/155658771-8d602f87-2b63-418e-ac32-2c8d8ac6a6cf.png)

I'm not sure that is intended.

2022-02-25 07:39 UTC, banananeko commented
Updated. Thank you so much for your very thorough explanation!

2022-02-25 08:16 UTC, jacogr approved these changes

2022-02-25 08:16 UTC, merged