[encointer] remove westend
polkadot-js/apps pull request #7103
Opened 2022-03-03 13:42 UTC by mosonyi

We have stopped our westend ( api.westend.encointer.org ), therefore deleted from config.

2022-03-03 13:51 UTC, jacogr approved these changes
A huge thanks for this PR, generally I need to hunt and pack these stoppages via issues that are created.

Having said that, as a common-good I don't see this as a good move - you are basically removing the only test avenue available. (For instance for teleports, it was tested on this avenue before merging.) Bear this in mind for future changes (e.g. XCM v3 is on the horizon), when it comes to real funds I generally don't play cowboy unless verified, so some features may be missing in the future where I cannot verify.

2022-03-03 13:52 UTC, jacogr requested changes
Tests most probably fail since the teleport destination is not removed for the relay, i.e. `[1000, 1001]` for the relay needs to change to `[1000]` only.

2022-03-03 14:30 UTC, jacogr approved these changes

2022-03-03 14:31 UTC, merged

2022-03-04 07:49 UTC, brenzi commented
@jacogr we will of course continue to test, but we were encouraged to move to rococo for future testing. So we didn't want infrastructure to idle around and shut down our westend infra.