Composable finance add dali to rococo
polkadot-js/apps pull request #7276
Opened 2022-03-30 14:11 UTC by alexkdefi

Hi!

Please add our Rococo network to apps.

2022-03-30 14:55 UTC, seunlanlege commented on packages/apps-config/src/ui/logos/index.ts
> +  'DaliTestnet based on Rococo' : chainRococoDali,
```suggestion
  'Dali Testnet (Rococo Relay)' : chainRococoDali,
```

2022-03-30 15:03 UTC, jacogr reviewed
One small housekeeping line removal. Apart from that, just ensure that Sean's comment is catered for - the name there needs to match with the chain name (as displayed and as from the RPC)

2022-03-30 15:03 UTC, jacogr commented on packages/apps-config/src/endpoints/testingRelayRococo.ts
> +
```suggestion
```

2022-03-31 06:51 UTC, alexkdefi commented
added suggested changes. Thanks!

2022-03-31 07:20 UTC, jacogr requested changes
Some CI failures (current and future once that is fixed)

2022-03-31 07:20 UTC, jacogr commented on packages/apps-config/src/endpoints/testingRelayRococo.ts
> +      {
Comma missing on previous line. 

CI will complain about this as well - the entries are expected to be alphabetical.

2022-03-31 13:24 UTC, jacogr requested changes
See https://github.com/polkadot-js/apps/runs/5771574589?check_suite_focus=true#step:3:697

2022-04-20 09:58 UTC, jacogr commented
I'm closing this since the last update has been 21 days ago and it is still failing. Would certainly like seeing this adjusted to pass CI check.

2022-04-20 09:58 UTC, closed without merging