Added Shiden Crowdloan 2
polkadot-js/apps pull request #7426
Opened 2022-04-22 17:07 UTC by akru

**Description**

This PR introduce empty endpoints for Shiden Network Crowdloan 2 (just add logo and title for parachain id).

2022-04-22 19:27 UTC, jacogr commented on packages/apps-config/src/endpoints/productionRelayKusama.ts
> +        providers: {}
Lemme just test this one - not sure how it behaves with empty providers. (Normally there is at least 1 + isUnreachable). This is certainly valid, but just concerned that I missed a trick in the filtering.

Will check/approve/comment in the morning.

2022-04-23 05:47 UTC, jacogr requested changes
Tested the comment here https://github.com/polkadot-js/apps/pull/7426/files#r856513007

Basically since there are no providers, it doesn't get added. The suggestion would be to add a provider entry but just add the `isUnreachable: true` flag to ensure it never gets used. (Assuming here that the endpoint is not running)

2022-04-25 01:43 UTC, akru commented
@jacogr thank you for feedback, fixed.

2022-04-25 04:20 UTC, jacogr approved these changes

2022-04-25 04:21 UTC, merged