feat(apps-config): introduce Jaz node
polkadot-js/apps pull request #7805
Opened 2022-06-27 23:39 UTC by gojazdev

## Summary

- [x] add Jaz endpoints
- [x] register ethereum chains
- [x] add Jaz colors
- [x] add Jaz logo

## Info

https://docs.jaz.network/guide/products

2022-06-27 23:39 UTC, gojazdev commented on .gitignore
> +.log
for the rls server of emacs

2022-06-28 04:59 UTC, jacogr approved these changes

2022-06-28 08:30 UTC, jacogr requested changes
CI is failing due to alphabetical ordering, see https://github.com/polkadot-js/apps/runs/7086149100?check_suite_focus=true#step:3:698

2022-07-01 04:39 UTC, jacogr approved these changes

2022-07-01 04:40 UTC, merged