Add snow to kusama endpoint option array
polkadot-js/apps pull request #7893
Opened 2022-07-20 13:39 UTC by 0xrust

2022-08-14 08:26 UTC, jacogr requested changes
CI is still failing, so cannot be merged.

2022-08-15 10:54 UTC, jacogr commented on packages/apps-config/src/endpoints/productionRelayKusama.ts
> +      IceNetwork: 'wss://snow-rpc.icenetwork.io',
```suggestion
      IceNetwork: 'wss://snow-rpc.icenetwork.io'
```

Trailing comma removed.

It also needs to be alphabetical.

2022-08-15 11:44 UTC, jacogr approved these changes

2022-08-15 11:44 UTC, merged

2022-08-15 14:13 UTC, susoreal commented
@jacogr the icon still not shows, do you have any hint on what the problem might be?

![image](https://user-images.githubusercontent.com/106300437/184651835-c0b42f98-774e-468b-a73e-9e412fbeb4fb.png)