add OAK chain
polkadot-js/apps pull request #8126
Opened 2022-09-14 15:47 UTC by justinzhou93

2022-09-14 21:04 UTC, irsal commented
@jacogr - please review 🙏

2022-09-15 08:27 UTC, jacogr requested changes

2022-09-15 08:27 UTC, jacogr commented on packages/apps-config/src/endpoints/productionRelayPolkadot.ts
> +  {
CI will fail here - it checks for the items being alphabetical

2022-09-15 15:52 UTC, jacogr approved these changes

2022-09-15 15:52 UTC, merged

2022-09-15 16:18 UTC, irsal commented on packages/apps-config/src/endpoints/productionRelayPolkadot.ts
> +    homepage: 'https://oak.tech',
`isUnreachable: true,`