Add Watr Polkadot
polkadot-js/apps pull request #9061
Opened 2023-02-23 15:43 UTC by NachoPal

This PR adds Watr Polkadot info to the already existing and producing blocks Watr Parachain.

2023-02-23 16:14 UTC, jacogr requested changes
Needs some adjustment, CI is failing on linting.

(And just noticed that GH helpfully shows exactly what is wrong in the code now as well on the "Files changed" view which is quite cool)

2023-02-23 16:22 UTC, NachoPal commented
> Needs some adjustment, CI is failing on linting.
> 
> (And just noticed that GH helpfully shows exactly what is wrong in the code now as well on the "Files changed" view which is quite cool)

Fixed :)

2023-02-23 17:18 UTC, jacogr approved these changes

2023-02-23 17:18 UTC, merged

2023-02-24 04:58 UTC, jacogr commented
Not available, will be removed after 4 appearances https://github.com/polkadot-js/apps/issues/9065