Added LuckyFriday's Kusama and Statemine RPC nodes
polkadot-js/apps pull request #9236
Opened 2023-03-28 07:33 UTC by paradox-tt

Dear PJS team,

Subsequent to our [treasury application](https://kusama.subsquare.io/council/motion/572) and successful rounds of testing the LuckyFriday team is seeking approval to have their RPC nodes listed within the Polkadot.JS application.  The RPC nodes are hosted on self-owned, newly acquired bare-metal servers hosted at a private Datacenter with bandwidth rated at 20 GBit (in/out/redundant).  We believe that LuckyFriday would be a good addition to the listing providing service outside of mainstream cloud and infrastructure providers.

We have spent the past few weeks load testing the servers using various sized payloads from from the staking and conviction voting pallets.  Tests were done at multiple geographic locations all to our satisfaction.  We also invited members of ChaosDAO to load test the endpoints and neither have broken.

Our monitoring stack comprises of Prometheus, Grafana and Alert Manager.  Alerts are sent to a common slack channel and if not attended to escalates to Pager-Duty calls.  Alerts are generated based on node unavailability or when there are 20 blocks behind finalization.  

I look forward to your feedback,

Kind Regards,
Will | Paradox

2023-03-28 07:39 UTC, jacogr commented
I would prefer that new RPC providers prove themselves on testnets first - once they are stable there for 2-ish weeks, can look at live Kusama/etc.

2023-03-28 07:43 UTC, paradox-tt commented
My apologies, I thought this was only necessary for those who were not already treasury approved.  We'll certainly comply.

Is your element address the same? I would like to share a segment of a proposal (related to this topic) that I'm putting together.

2023-03-28 07:45 UTC, jacogr commented
No issues. I'm more worried about overhead, not what treasury approved or didn't - [see here](https://github.com/polkadot-js/apps/issues?q=is%3Aissue+is%3Aclosed+label%3Aci).

2023-04-17 12:49 UTC, paradox-tt commented
Hi Jaco,

Just a reminder that two weeks have elapsed since we've been operating [on Westend](https://github.com/polkadot-js/apps/pull/9284).

I would also like to take the opportunity to share with you [a proposal](https://docs.google.com/document/d/1us8glHDEaXeqNp0Ex8Z5sffy4GTfhrvHzGNzNvp-juw/edit) that is currently at the [discussion phase](https://kusama.polkassembly.io/post/2546).  Part of the scope seeks to monitor and present a history of uptime, performance and integrity of RPC/WSS endpoints.  I hope that it is useful to you and the broader community in some way.

2023-04-20 05:55 UTC, jacogr requested changes
Some small linting fixes required.

2023-04-20 15:19 UTC, paradox-tt commented
Removed the extra quotes

2023-04-20 15:29 UTC, paradox-tt commented
All done, yay!

2023-04-20 17:27 UTC, jacogr approved these changes
Thank you.

2023-04-20 17:27 UTC, merged