Updated Polkadex Parachain endpoint
polkadot-js/apps pull request #9430
Opened 2023-05-11 08:22 UTC by zktony

This PR will update the Polkadex Parachain endpoint.

2023-05-11 08:59 UTC, jacogr commented on packages/apps-config/src/endpoints/productionRelayPolkadot.ts
>      isUnreachable: true,
```suggestion
```

We should remove this as well, since we now should have reachable endpoints.

2023-05-11 08:59 UTC, jacogr commented on packages/apps-config/src/endpoints/productionRelayPolkadot.ts
> +      Polkadex: 'wss://parachain.polkadex.trade/',
```suggestion
      Polkadex: 'wss://parachain.polkadex.trade/'
```

Linting fix.

2023-05-11 09:00 UTC, jacogr requested changes
Thank you. Some small changes. (linting & reachable)

2023-06-09 09:31 UTC, zktony commented
Hey @jacogr, I resolved all the comments. Could you please review it?

2023-06-19 07:30 UTC, merged