Add darwinia community provider
polkadot-js/apps pull request #9556
Opened 2023-06-08 16:37 UTC by fewensa

2023-06-08 17:13 UTC, jacogr requested changes
Needs ordering fixes as indicated by the linting comments.

2023-06-09 02:12 UTC, fewensa commented
cc @1022ranji

2023-06-09 02:13 UTC, fewensa commented
> Needs ordering fixes as indicated by the linting comments.

Done, I'm changed Darwinia Network to Darwinia

2023-06-09 14:24 UTC, jacogr approved these changes

2023-06-09 14:24 UTC, merged